theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
cursorline = true
rulers = [120]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-messages = true


[editor.statusline]
center = []
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
left = ["mode", "spinner", "file-name"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

######################################### 
######################################### 
####             KEYBINDS            #### 
######################################### 
######################################### 

[keys.normal]
# 
# Shared with insert mode 
# 
"F1" = "toggle_line_comments"
"F2" = ":format"
C-s = ":write"

#
# Shared with select mode
# 
"C-up" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ] # Move current selection up
"C-down" = [ "extend_to_line_bounds", "delete_selection", "paste_after"] # Move current selection down

# 
# normal binds
# 
tab = ":buffer-next"
S-tab = ":buffer-previous"
esc = ["collapse_selection", "keep_primary_selection"]

# Create a cursor above / below
S-up = "copy_selection_on_prev_line"
S-down = "copy_selection_on_next_line"

C-c = ["extend_to_line_bounds", "yank", ":clipboard-yank"] # Copy whole current line

[keys.normal.space]
x = ":buffer-close"
space = "keep_primary_selection"
# c = ["extend_to_line_bounds", "yank"]
# v = "paste_after"

[keys.insert]
#
# Shared with normal mode
# 
"F1" = "toggle_line_comments"
"F2" = ":format"
C-s = ":write"
C-c = ["extend_to_line_bounds", "yank", ":clipboard-yank"] # Copy whole current line

C-ret = ["normal_mode","open_below"]

[keys.select]
y = [":clipboard-yank", "yank"]

# 
# Shared with normal mode
# 
"C-up" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ] # Move current selection up
"C-down" = [ "extend_to_line_bounds", "delete_selection", "paste_after"] # Move current selection down
