######################################### 
######################################### 
####               RUST              #### 
######################################### 
######################################### 

[[language]]
name = "rust"
scope = "source.rust"

[language-server.rust-analyzer.config]
hostInfo = "rust"
locale = "en-GB"
check.command = "clippy"

[language-server.rust-analyzer.config.inlayHints]
closureReturnTypeHints.enable = "always"
lifetimeElisionHints = { enable = "skip_trivial", useParameterNames = true }
# includeInlayEnumMemberValueHints = true

[language-server.rust-analyzer.config.imports]
granularity = { enforce = true, group = "crate" }

# includeInlayFunctionLikeReturnTypeHints = true
# includeInlayFunctionParameterTypeHints = true
# includeInlayParameterNameHints = "all"                       # 'none' | 'literals' | 'all';
# includeInlayParameterNameHintsWhenArgumentMatchesName = true
# includeInlayPropertyDeclarationTypeHints = true
# includeInlayVariableTypeHints = true

# expressionAdjustmentHints = { enable = true, mode = "postfix" }
# genericParameterHints = { type = { enable = true }, lifetime = { enable = true } }

# [language-server.rust-analyzer.config.inlayHints.lifetimeElisionHints]
# enable = true
# useParameterNames = true
# [language.auto-pairs]
# '<' = '>'
# "'" = { close = "'", except_prefixes = ["<", "&"] }
[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
# '`' = '`'
'<' = '>'
"'" = "'"

######################################### 
######################################### 
####              PYTHON             #### 
######################################### 
######################################### 


[[language]]
name = "python"
language-servers = ["pylsp", "ruff", "pylint"]
formatter = { command = "black", args = ["-"] }
# roots = [".git"]
# workspace-lsp-roots = ["src/updater"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
flake8 = { enabled = true, ignore = ["E501"] }
autopep8 = { enabled = false }
mccabe = { enabled = false }
pycodestyle = { enabled = false }
pyflakes = { enabled = false }
pylint = { enabled = true }
yapf = { enabled = false }
ruff = { enabled = true }

[language-server.ruff]
enabled = true
command = "ruff"
args = ["server"]

[language-server.pylint]
enabled = true
command = "pylint"
# args = ["server"]


######################################### 
######################################### 
####               TOML              #### 
######################################### 
######################################### 

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }
