######################################### 
######################################### 
####               RUST              #### 
######################################### 
######################################### 

[[language]]
name = "rust"

[language.config]
hostInfo = "rust"
locale = "en-GB"

[language-server.rust-analyzer.config]
check.command = "clippy"

[language.config.rust.inlayHints]
includeInlayEnumMemberValueHints = false
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "all"                       # 'none' | 'literals' | 'all';
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true



######################################### 
######################################### 
####              PYTHON             #### 
######################################### 
######################################### 

[[language]]
name = "python"
language-servers = ["pylsp"]

[language-server.pylsp.config.pylsp]
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = true
plugins.flake8.maxLineLength = 120
plugins.pycodestyle.maxLineLength = 120

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]


[[language]]
name = "python"
language-servers = ["pylsp"]
# roots = [".git"]
# workspace-lsp-roots = ["src/updater"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = true, ignore = ["E501"]}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = true}
yapf = {enabled = false}
ruff = { enabled = false}
