[[language]]
name = "rust"

[language.config]
hostInfo = "rust"
locale = "en-GB"

[language-server.rust-analyzer.config]
check.command = "clippy"

[language.config.rust.inlayHints]
includeInlayEnumMemberValueHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "all"                       # 'none' | 'literals' | 'all';
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true

