######################################### 
######################################### 
####               RUST              #### 
######################################### 
######################################### 
# rustup component add rust-analyzer
[[language]]
name = "rust"
scope = "source.rust"
auto-format = false

[language-server.rust-analyzer.config]
hostInfo = "rust"
locale = "en-GB"
check.command = "clippy"

[language-server.rust-analyzer.config.inlayHints]
closureReturnTypeHints.enable = "always"
lifetimeElisionHints = { enable = "skip_trivial", useParameterNames = true }
# includeInlayEnumMemberValueHints = true

[language-server.rust-analyzer.config.imports]
granularity = { enforce = true, group = "crate" }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
# '`' = '`'
'<' = '>'
# "'" = { close = "'", except_prefixes = ["<", "&"] }
# "'" = "'"

######################################### 
######################################### 
####        Rust crates version      #### 
######################################### 
######################################### 
# https://blog.katona.me/2025/01/12/Adding-crates-io-version-check-to-Helix-editor/
#
# cargo install --git https://github.com/MathiasPius/crates-lsp.git --rev 53fb3b8d58c43ea799fdbc1fd28fa5db3f01b01a
# cp -r /usr/<lib or lib64>/helix/runtime/queries/toml ~/.config/helix/runtime/queries/crates
[[language]]
name = "crates"
scope = "source.toml"
injection-regex = "toml"
file-types = [{ glob = "Cargo.toml" }]
comment-token = "#"
language-servers = [
  { name = "crates-lsp", except-features = [
    "format",
  ] },
  "taplo",
]
grammar = "toml"
indent = { tab-width = 2, unit = "  " }
diagnostic-severity = "info"
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.crates-lsp]
command = "crates-lsp"

######################################### 
######################################### 
####               TOML              #### 
######################################### 
######################################### 
# cargo install taplo-cli --locked --features lsp
[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

######################################### 
######################################### 
####              PYTHON             #### 
######################################### 
#########################################
# pip install pylint
# pip install "python-lsp-server[all]"
[[language]]
name = "python"
language-servers = ["pylsp"]
formatter = { command = "black", args = ["-"] }
# roots = [".git"]
# workspace-lsp-roots = ["src/updater"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
flake8 = { enabled = false, ignore = ["E501"] }
autopep8 = { enabled = false }
mccabe = { enabled = false }
pycodestyle = { enabled = false }
pyflakes = { enabled = false }
pylint = { enabled = true }
yapf = { enabled = false }
ruff = { enabled = false }

[language-server.ruff]
enabled = false
command = "ruff"
args = ["server"]

[language-server.pylint]
enabled = true
command = "pylint"
# args = ["server"]
